### ISSUE TITLE
Informazioni

### ISSUE THREAD

**Issue by TheOfficialDragone** [davbianchi/dispense-info-univr#17]
Ciao, ho visto che c'è la dispensa di sicurezza delle reti, è il corso che teneva Merro?

**Comment by sentientmachin3** [comment]
Ciao, ce ne sono due, uno in triennale e uno in magistrale. Se intendi quello in magistrale é di Merro, quello in triennale di Carra. 

Tieni presente che sono passati un po' di anni (~6) quindi non so quanto siano aggiornate a livello di programma.

**Comment by TheOfficialDragone** [comment]
Ciao,
Devo dare l’esame di Merro in magistrale (ingegneria delle scienze informatiche), sto giusto guardando le tue dispense di sicurezza, sono molto complete in realtà… perché fondamentalmente è sempre la stessa roba che fa: Ipsec, PKI, Kerberos ecc ecc.
Quindi grazie mille mi hai salvato il c… !
Rocco Carpi
Inviato da MacBook Pro

Il testo e gli eventuali documenti trasmessi contengono informazioni riservate al destinatario indicato. La seguente e-mail è confidenziale e la sua riservatezza è tutelata dal codice della privacy art.13 del D.Lgl. 30.6.2003 n°196 (Reg EU 2006/691). La lettura, copia od altro uso non autorizzato o qualsiasi altra azione derivante dalla conoscenza di queste informazioni sono rigorosamente vietate.


Il giorno 29 mag 2024, alle ore 11:03, Davide Bianchi ***@***.***> ha scritto:



Ciao, ce ne sono due, uno in triennale e uno in magistrale. Se intendi quello in magistrale é di Merro, quello in triennale di Carra.

Tieni presente che sono passati un po' di anni (~6) quindi non so quanto siano aggiornate a livello di programma.
